wshom/forms.py
import flask_wtf
import wtforms
import wtforms.fields.html5
import wtforms.validators
from wshom.model import User
from flask_login import current_user
import pytz
import string

class LoginForm(flask_wtf.FlaskForm):
    username = wtforms.StringField("Username", validators=[wtforms.validators.DataRequired()])
    password = wtforms.PasswordField("Password", validators=[wtforms.validators.DataRequired()])
    submit = wtforms.SubmitField("Sign In")

class RegisterForm(flask_wtf.FlaskForm):
    username = wtforms.StringField("Username", validators=[wtforms.validators.DataRequired(), wtforms.validators.Length(min=3, max=10)])
    password = wtforms.PasswordField("Password", validators=[wtforms.validators.Length(min=6)])
    password2 = wtforms.PasswordField("Re-type password", validators=[wtforms.validators.DataRequired(), wtforms.validators.EqualTo("password", message="Passwords do not match")])
    email = wtforms.fields.html5.EmailField("Email", validators=[wtforms.validators.Email()])
    submit = wtforms.SubmitField("Register")

    def validate_email(self, field):
        if User.query.filter_by(email=self.email.data).first():
            raise wtforms.ValidationError("Email already in use")

    def validate_username(self, field):
        allowed_characters = string.ascii_lowercase + string.digits + "_"

        if any(c not in allowed_characters for c in self.username.data):
            raise wtforms.ValidationError("Username may only contain lowercase letters, digits, and undescores.")

        if User.query.filter_by(username=self.username.data).first():
            raise wtforms.ValidationError("Username already taken")

class AddFriendForm(flask_wtf.FlaskForm):
    add_username = wtforms.StringField("Username", validators=[wtforms.validators.DataRequired()])
    submit_add = wtforms.SubmitField("Add Friend")

    def validate_add_username(self, field):
        user = User.query.filter_by(username=self.add_username.data).first()
        if user is None:
            raise wtforms.ValidationError("User not found")
        if user == current_user:
            raise wtforms.ValidationError("That's you")
        if user in current_user.friends:
            raise wtforms.ValidationError("User is already a friend")

class DeleteFriendForm(flask_wtf.FlaskForm):
    delete_username = wtforms.HiddenField("Username", validators=[wtforms.validators.DataRequired()])
    submit_delete = wtforms.SubmitField("[X]")

    def validate_delete_username(self, field):
        user = User.query.filter_by(username=self.delete_username.data).first()
        if user is None:
            raise wtforms.ValidationError("User not found")
        if user == current_user:
            raise wtforms.ValidationError("That's you")
        if user not in current_user.friends:
            raise wtforms.ValidationError("User is not a friend")

class ProfileForm(flask_wtf.FlaskForm):
    tz_choices = [("", "unspecified")] + [(tzname, tzname.replace("_", " ")) for tzname in pytz.common_timezones]

    email = wtforms.StringField("Email", validators=[wtforms.validators.Email()])
    display_name = wtforms.StringField("Display Name", validators=[wtforms.validators.Length(max=240)])
    timezone = wtforms.SelectField("Timezone", choices=tz_choices, validators=[wtforms.validators.AnyOf(set(val for (val, _) in tz_choices), "Not a valid timezone")])
    min_interval = wtforms.fields.html5.IntegerField("Minimum interval between hangouts (days)", validators=[wtforms.validators.NumberRange(3, 12, "Value must be between %(min)s and %(max)s")])
    active = wtforms.BooleanField("Active")
    submit = wtforms.SubmitField("Update")

    def validate_email(self, field):
        if User.query.filter_by(email=self.email.data).first():
            raise wtforms.ValidationError("Email already in use")

wshom/__init__.py
import flask
import flask_sqlalchemy
import wshom.config
from wshom.extensions import db, login_manager
import wshom.config
import wshom.views
import wshom.graph

def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)

def register_blueprints(app):
    app.register_blueprint(wshom.views.blueprint)

def create_app():
    app = flask.Flask(__name__)
    app.config.from_object(wshom.config.Config)
    register_extensions(app)
    register_blueprints(app)
    return app

def create_db(app):
    with app.app_context():
        db.create_all()

def arrange_hangouts(app):
    with app.app_context():
        wshom.graph.arrange_hangouts(app)

wshom/views.py
import flask
from flask import Blueprint
import flask_login
import werkzeug.security
from wshom.model import User
from wshom.extensions import db, login_manager
import wshom.forms
from flask_login import current_user

blueprint = Blueprint("public", __name__, static_folder="../static")

login_manager.login_view = "public.login"

@blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = wshom.forms.LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flask.flash("Invalid username or password")
            return flask.redirect(flask.url_for("public.login"))
        else:
            flask_login.login_user(user, remember=True)
            return flask.redirect(flask.url_for("public.index"))
    return flask.render_template("login.html", form=form)

@blueprint.route("/logout", methods=["POST"])
def logout():
    flask_login.logout_user()
    return flask.redirect(flask.url_for("public.index"))

@blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = wshom.forms.RegisterForm()
    if form.validate_on_submit():
        password_hash = werkzeug.security.generate_password_hash(form.password.data)
        user = User(username=form.username.data,
                    password_hash=password_hash,
                    email=form.email.data)
        db.session.add(user)
        db.session.commit()
        flask.flash("Registered!")
        flask_login.login_user(user, remember=True)
        return flask.redirect(flask.url_for("public.profile"))
    else:
        return flask.render_template("register.html", form=form)

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

@blueprint.route("/")
def index():
    return flask.render_template("index.html")

@blueprint.route("/friends", methods=["GET", "POST"])
@flask_login.login_required
def friends():
    add_friend_form = wshom.forms.AddFriendForm()
    delete_friend_form = wshom.forms.DeleteFriendForm()

    if add_friend_form.submit_add.data and add_friend_form.validate_on_submit():
        user = User.query.filter_by(username=add_friend_form.add_username.data).one()
        current_user.friends.append(user)
        db.session.commit()

    if delete_friend_form.submit_delete.data and delete_friend_form.validate_on_submit():
        user = User.query.filter_by(username=delete_friend_form.delete_username.data).one()
        current_user.friends.remove(user)
        db.session.commit()

    friends = current_user.friends
    delete_friend_forms = [wshom.forms.DeleteFriendForm(delete_username=f.username) for f in friends]
    return flask.render_template("friends.html", add_friend_form=add_friend_form, friends=zip(friends, delete_friend_forms), delete_friend_form=delete_friend_form)

@blueprint.route("/profile", methods=["GET", "POST"])
@flask_login.login_required
def profile():
    form = wshom.forms.ProfileForm(email=current_user.email, display_name=current_user.display_name, timezone=current_user.timezone, min_interval=current_user.min_interval, active=current_user.active)
    if form.validate_on_submit():
        current_user.email = form.email.data
        current_user.display_name = form.display_name.data
        current_user.timezone = form.timezone.data
        current_user.min_interval = form.min_interval.data
        current_user.active = form.active.data
        db.session.commit()
        flask.flash("Profile updated")
    return flask.render_template("profile.html", form=form)

wshom/templates/base.html
<html>
<head>
<title>{{ title }}</title>
</head>
<body>
{% if current_user.is_anonymous %}
<a href="{{ url_for('public.login') }}">Login</a> or <a href="{{ url_for('public.register') }}">Register</a>
{% else %}
<p>Logged in as {{ current_user.username }}</p>
<form action="{{ url_for('public.logout') }}" method="post"><input type="submit" value="Logout"></form>
<ul>
    <li><a href="{{ url_for('public.profile') }}">Profile</a></li>
    <li><a href="{{ url_for('public.friends') }}">Friends</a></li>
</ul>
{% endif %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
<h1>{{ title }}</h1>
{% block content %}
{% endblock %}
</body>
</html>

wshom/templates/friends.html
{% extends "base.html" %}

{% set title = "Friends" %}

{% block content %}
    <h2>Add a friend</h2>
    <form action="" method="post" novalidate>
        {{ add_friend_form.hidden_tag() }}
        <p>
            {{ add_friend_form.add_username.label }}<br>
            {{ add_friend_form.add_username(size=32) }}<br>
            {% for error in add_friend_form.add_username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ add_friend_form.submit_add() }}</p>
    </form>

    <h2>Current friends</h2>
    <ul>
{% for user, form in friends %}
        <li>
            <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            {{ user.username }}
            {{ form.delete_username }}
            {{ form.submit_delete() }}
            </form>
        </li>
        {% for error in delete_friend_form.delete_username.errors %}
        <p><span style="color: red;">[{{ error }}]</span></p>
        {% endfor %}
{% else %}
    <li>No friends yet!</li>
{% endfor %}
    </ul>
{% endblock %}

wshom/templates/index.html
{% extends "base.html" %}

{% set title = "Home" %}

{% block content %}
We should hang out more
{% endblock %}

wshom/templates/login.html
{% extends "base.html" %}

{% set title = "Login" %}

{% block content %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

wshom/templates/profile.html
{% extends "base.html" %}

{% set title = "Profile" %}

{% block content %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
{% for field in ["email", "display_name", "timezone", "min_interval", "active"] %}
        <p>
            {{ form[field].label }}<br>
            {{ form[field] }}<br>
            {% for error in form[field].errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
{% endfor %}
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

wshom/templates/register.html
{% extends "base.html" %}

{% set title = "Register" %}

{% block content %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}